version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5439:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6377:6379"
    volumes:
      - redis_data:/data

  api:
    build:
      context: .
      dockerfile: apps/hono/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5439/inventory
      - REDIS_PORT=6377
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data:
