/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardLayoutImport } from './routes/dashboard/layout'
import { Route as AuthLayoutImport } from './routes/auth/layout'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as AuthVerifyEmailImport } from './routes/auth/verify-email'
import { Route as AuthSignupImport } from './routes/auth/signup'
import { Route as DashboardTeamLayoutImport } from './routes/dashboard/team/layout'
import { Route as DashboardCategoriesLayoutImport } from './routes/dashboard/categories/layout'
import { Route as DashboardAuditlogsLayoutImport } from './routes/dashboard/auditlogs/layout'
import { Route as DashboardTeamIndexImport } from './routes/dashboard/team/index'
import { Route as DashboardInventoryIndexImport } from './routes/dashboard/inventory/index'
import { Route as DashboardCategoriesIndexImport } from './routes/dashboard/categories/index'
import { Route as DashboardAuditlogsIndexImport } from './routes/dashboard/auditlogs/index'
import { Route as DashboardTeamTeamImport } from './routes/dashboard/team/$team'

// Create/Update Routes

const DashboardLayoutRoute = DashboardLayoutImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AuthLayoutRoute = AuthLayoutImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthVerifyEmailRoute = AuthVerifyEmailImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const DashboardTeamLayoutRoute = DashboardTeamLayoutImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const DashboardCategoriesLayoutRoute = DashboardCategoriesLayoutImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const DashboardAuditlogsLayoutRoute = DashboardAuditlogsLayoutImport.update({
  id: '/auditlogs',
  path: '/auditlogs',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const DashboardTeamIndexRoute = DashboardTeamIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardTeamLayoutRoute,
} as any)

const DashboardInventoryIndexRoute = DashboardInventoryIndexImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const DashboardCategoriesIndexRoute = DashboardCategoriesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardCategoriesLayoutRoute,
} as any)

const DashboardAuditlogsIndexRoute = DashboardAuditlogsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAuditlogsLayoutRoute,
} as any)

const DashboardTeamTeamRoute = DashboardTeamTeamImport.update({
  id: '/$team',
  path: '/$team',
  getParentRoute: () => DashboardTeamLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/auditlogs': {
      id: '/dashboard/auditlogs'
      path: '/auditlogs'
      fullPath: '/dashboard/auditlogs'
      preLoaderRoute: typeof DashboardAuditlogsLayoutImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/categories': {
      id: '/dashboard/categories'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof DashboardCategoriesLayoutImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamLayoutImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof AuthLayoutImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailImport
      parentRoute: typeof AuthLayoutImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthLayoutImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/team/$team': {
      id: '/dashboard/team/$team'
      path: '/$team'
      fullPath: '/dashboard/team/$team'
      preLoaderRoute: typeof DashboardTeamTeamImport
      parentRoute: typeof DashboardTeamLayoutImport
    }
    '/dashboard/auditlogs/': {
      id: '/dashboard/auditlogs/'
      path: '/'
      fullPath: '/dashboard/auditlogs/'
      preLoaderRoute: typeof DashboardAuditlogsIndexImport
      parentRoute: typeof DashboardAuditlogsLayoutImport
    }
    '/dashboard/categories/': {
      id: '/dashboard/categories/'
      path: '/'
      fullPath: '/dashboard/categories/'
      preLoaderRoute: typeof DashboardCategoriesIndexImport
      parentRoute: typeof DashboardCategoriesLayoutImport
    }
    '/dashboard/inventory/': {
      id: '/dashboard/inventory/'
      path: '/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof DashboardInventoryIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/team/': {
      id: '/dashboard/team/'
      path: '/'
      fullPath: '/dashboard/team/'
      preLoaderRoute: typeof DashboardTeamIndexImport
      parentRoute: typeof DashboardTeamLayoutImport
    }
  }
}

// Create and export the route tree

interface AuthLayoutRouteChildren {
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface DashboardAuditlogsLayoutRouteChildren {
  DashboardAuditlogsIndexRoute: typeof DashboardAuditlogsIndexRoute
}

const DashboardAuditlogsLayoutRouteChildren: DashboardAuditlogsLayoutRouteChildren =
  {
    DashboardAuditlogsIndexRoute: DashboardAuditlogsIndexRoute,
  }

const DashboardAuditlogsLayoutRouteWithChildren =
  DashboardAuditlogsLayoutRoute._addFileChildren(
    DashboardAuditlogsLayoutRouteChildren,
  )

interface DashboardCategoriesLayoutRouteChildren {
  DashboardCategoriesIndexRoute: typeof DashboardCategoriesIndexRoute
}

const DashboardCategoriesLayoutRouteChildren: DashboardCategoriesLayoutRouteChildren =
  {
    DashboardCategoriesIndexRoute: DashboardCategoriesIndexRoute,
  }

const DashboardCategoriesLayoutRouteWithChildren =
  DashboardCategoriesLayoutRoute._addFileChildren(
    DashboardCategoriesLayoutRouteChildren,
  )

interface DashboardTeamLayoutRouteChildren {
  DashboardTeamTeamRoute: typeof DashboardTeamTeamRoute
  DashboardTeamIndexRoute: typeof DashboardTeamIndexRoute
}

const DashboardTeamLayoutRouteChildren: DashboardTeamLayoutRouteChildren = {
  DashboardTeamTeamRoute: DashboardTeamTeamRoute,
  DashboardTeamIndexRoute: DashboardTeamIndexRoute,
}

const DashboardTeamLayoutRouteWithChildren =
  DashboardTeamLayoutRoute._addFileChildren(DashboardTeamLayoutRouteChildren)

interface DashboardLayoutRouteChildren {
  DashboardAuditlogsLayoutRoute: typeof DashboardAuditlogsLayoutRouteWithChildren
  DashboardCategoriesLayoutRoute: typeof DashboardCategoriesLayoutRouteWithChildren
  DashboardTeamLayoutRoute: typeof DashboardTeamLayoutRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardInventoryIndexRoute: typeof DashboardInventoryIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardAuditlogsLayoutRoute: DashboardAuditlogsLayoutRouteWithChildren,
  DashboardCategoriesLayoutRoute: DashboardCategoriesLayoutRouteWithChildren,
  DashboardTeamLayoutRoute: DashboardTeamLayoutRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardInventoryIndexRoute: DashboardInventoryIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/dashboard/auditlogs': typeof DashboardAuditlogsLayoutRouteWithChildren
  '/dashboard/categories': typeof DashboardCategoriesLayoutRouteWithChildren
  '/dashboard/team': typeof DashboardTeamLayoutRouteWithChildren
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/team/$team': typeof DashboardTeamTeamRoute
  '/dashboard/auditlogs/': typeof DashboardAuditlogsIndexRoute
  '/dashboard/categories/': typeof DashboardCategoriesIndexRoute
  '/dashboard/inventory': typeof DashboardInventoryIndexRoute
  '/dashboard/team/': typeof DashboardTeamIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/team/$team': typeof DashboardTeamTeamRoute
  '/dashboard/auditlogs': typeof DashboardAuditlogsIndexRoute
  '/dashboard/categories': typeof DashboardCategoriesIndexRoute
  '/dashboard/inventory': typeof DashboardInventoryIndexRoute
  '/dashboard/team': typeof DashboardTeamIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/dashboard/auditlogs': typeof DashboardAuditlogsLayoutRouteWithChildren
  '/dashboard/categories': typeof DashboardCategoriesLayoutRouteWithChildren
  '/dashboard/team': typeof DashboardTeamLayoutRouteWithChildren
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/team/$team': typeof DashboardTeamTeamRoute
  '/dashboard/auditlogs/': typeof DashboardAuditlogsIndexRoute
  '/dashboard/categories/': typeof DashboardCategoriesIndexRoute
  '/dashboard/inventory/': typeof DashboardInventoryIndexRoute
  '/dashboard/team/': typeof DashboardTeamIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/auditlogs'
    | '/dashboard/categories'
    | '/dashboard/team'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/auth/'
    | '/dashboard/'
    | '/dashboard/team/$team'
    | '/dashboard/auditlogs/'
    | '/dashboard/categories/'
    | '/dashboard/inventory'
    | '/dashboard/team/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/auth'
    | '/dashboard'
    | '/dashboard/team/$team'
    | '/dashboard/auditlogs'
    | '/dashboard/categories'
    | '/dashboard/inventory'
    | '/dashboard/team'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/auditlogs'
    | '/dashboard/categories'
    | '/dashboard/team'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/auth/'
    | '/dashboard/'
    | '/dashboard/team/$team'
    | '/dashboard/auditlogs/'
    | '/dashboard/categories/'
    | '/dashboard/inventory/'
    | '/dashboard/team/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth",
        "/dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth": {
      "filePath": "auth/layout.tsx",
      "children": [
        "/auth/signup",
        "/auth/verify-email",
        "/auth/"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard/layout.tsx",
      "children": [
        "/dashboard/auditlogs",
        "/dashboard/categories",
        "/dashboard/team",
        "/dashboard/",
        "/dashboard/inventory/"
      ]
    },
    "/dashboard/auditlogs": {
      "filePath": "dashboard/auditlogs/layout.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/auditlogs/"
      ]
    },
    "/dashboard/categories": {
      "filePath": "dashboard/categories/layout.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/categories/"
      ]
    },
    "/dashboard/team": {
      "filePath": "dashboard/team/layout.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/team/$team",
        "/dashboard/team/"
      ]
    },
    "/auth/signup": {
      "filePath": "auth/signup.tsx",
      "parent": "/auth"
    },
    "/auth/verify-email": {
      "filePath": "auth/verify-email.tsx",
      "parent": "/auth"
    },
    "/auth/": {
      "filePath": "auth/index.tsx",
      "parent": "/auth"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/team/$team": {
      "filePath": "dashboard/team/$team.tsx",
      "parent": "/dashboard/team"
    },
    "/dashboard/auditlogs/": {
      "filePath": "dashboard/auditlogs/index.tsx",
      "parent": "/dashboard/auditlogs"
    },
    "/dashboard/categories/": {
      "filePath": "dashboard/categories/index.tsx",
      "parent": "/dashboard/categories"
    },
    "/dashboard/inventory/": {
      "filePath": "dashboard/inventory/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/team/": {
      "filePath": "dashboard/team/index.tsx",
      "parent": "/dashboard/team"
    }
  }
}
ROUTE_MANIFEST_END */
