import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./v1.d"; // generated by openapi-typescript

const fetchClient = createFetchClient<paths>({
  baseUrl: "http://localhost:5000/v1/",
});
export const apiQuery = createClient(fetchClient);

// inventoryQuery.useSuspenseQuery("get","/api/v1/auth/me")
